apiVersion: v2
name: windforlife
description: The WindForLife Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "~12.1.3" # ~12.1.3 is equivalent to >= 12.1.3, < 12.2.0
    condition: postgresql.selfManaged.enabled
    # version: "~10.3.13" # ~10.3.13 is equivalent to >= 10.3.13, < 10.4.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: "~17.3.16" # ~17.3.16 is equivalent to >= 17.3.16, < 17.4.0
    # version: "~12.8.3" # ~12.8.3 is equivalent to >= 12.8.3, < 12.9.0 --> Deprecated
