{{- if not .Values.postgresql.selfManaged.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-app
  labels:
    {{- include "windforlife.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.externalPostgresql.postgresqlPassword | quote }}
{{- end }}
